name: Repo Initer

on:
    schedule:
        - cron: '0 0 * * 0'
    workflow_dispatch:

jobs:
    refresh:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo content
              uses: actions/checkout@v4

            - name: dowload and extract files and commit
              run: |
                  wget ${{ secrets.URL_DOWNLOAD }} -O files.tar.gz
                  tar -xzf files.tar.gz
                  git config --local user.email "action@github.com"
                  git config --local user.name "Auto-Updater"
                  git add --all sampark.gov.in/
                  git diff-index --quiet HEAD || (git commit -a -m "Data auto-update" --allow-empty)
                
            - name: push changes
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  branch: main 
